# Macro file for the initialization
# in interactive session
/control/macroPath /home/john/Documents/projects/Github/muon_lab_simulation/build/macros
#
# Set some default verbose
/control/verbose 0
/control/saveHistory
/run/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
